### PR TITLE
IISCRUM-3083 Maintenance preview

### PR DESCRIPTION
**Pull request by rwdigia**

### CODE REVIEW

**Comment by bulkware** [comment]
Code looks clean, but I would like some more commenting. I have no idea what those if-clauses do... :)

**Review by blindBombus — APPROVED** [review]
Nothing particular pops up so I think code is OK. What I would do is I would add some well named constants for numerals so when for example there is comparison of maintenanceMode to some number, you could constant with the name of the mode instead of just numbers. So instead of **if(maintenanceMode='1')** you could have **if(maintenanceMode=REPEATING_MAINTENANCE)**. Keep it simple, keep it clean. And add some comments so there won't be too many _secrets that only fire can tell_.

**Comment by rwdigia** [comment]
Added a few comments and updated maintenance mode to use constants instead of variables.

Please note that the latter is not by my design so I hope I got it right. For some reason there was a mix of strings and numbers in addition to strict checking. I updated so that only numbers are used.

**Review by blindBombus — APPROVED** [review]
Readability +100%

**Review by bulkware — APPROVED** [review]

**Comment by bulkware** [comment]
We agreed yesterday that the comments should still be kept in code, but the globals are to be removed since those introduced bugs.

**Pull request merged**
